### ISSUE TITLE
Remove passed value to get IP address

### ISSUE THREAD

**Issue by tripflex** [mamuesp/common-tools#2]
https://github.com/mamuesp/common-tools/blob/904a362a012a03bc995841372f5dcafef9154543/mjs_fs/api_common.js#L222

The `0` should be removed, as nothing should be passed based on the C code

**Comment by mamuesp** [comment]
Fixed with commit [#6589013](https://github.com/mamuesp/common-tools/commit/65890131ede24118c4ed93009c0131cc3166595e)
